### ISSUE TITLE
Rationale

### ISSUE THREAD

**Issue by shaunmcpherson** [shaunmcpherson/just-your-type#1]
For this assignment, I selected part of a quote famously spoken by Steve Jobs. I had chosen it because I felt that it was on that many would be familiar with, but also one that is expressive and relates to us in our program as creators. For my concept, I placed the sentence in the very center of the page with the reference to the speaker’s name below it, flush right. The sentence has been broken up into three phrases, each of which placed on it’s own line, and with a key word highlighted in a different colour. The main idea was to have the keywords change in a way that relate to the keyword itself, while at the same time visually de-emphasizing the rest of the text around it.

For the final product, I ended up using several different typefaces, one for the quote, including the keywords in their default state, and a number of others for the keywords themselves in their hovered states. For the primary typeface, I wanted to use something that looked similar to _Helvetica_, the typeface used by apple in the majority of their promotional materials, so I elected to _Sen_, a Google font that shares a lot of similar attributes. When hovered, the first keyword “crazy” changes to the typeface _Permanent Marker_, a typeface with more variation in it’s construction which contributes to a “rougher” appearance. I wanted something that matched the word thematically while remaining uniform enough to not look out of place. The next keyword, “change”, uses several typefaces in addition to _Sen_: _Pacifico_, _Homemade Apple_ and _Damion_. The concept with this word was to have the typeface cycle through each of these script fonts to convey the meaning of the word visually. For the third and final keyword, “do”, I wanted for the changes to be the most significant as this is the final word of the entire quote and serves as the action word. In this instance, I chose the typeface _Bungee Shade_ and changed the text to all uppercase. This typeface is a dramatic departure from the others used in the rest of this design with many elements to its construction, such as an outline and a drop shadow. To further emphasize this change, the word also grows in size, setting it even further apart from the rest of the text.

Continuing in the Apple design aesthetic that I was aiming for, the overall layout is fairly monotone, with black text set on top of a white background. The only exception to this is with the three keywords which are each underlined in a different colour: red, gold, and green. This was done in order to show the viewer where the key elements of the site were, giving a hint as to where the changes would be found with a hover. Upon hovering, each of these words change to the colour that matches their underline, while the underline itself disappears. With the word “crazy”, however, I’ve used and animation that has the word alternate between black and red with an under glow that makes it appear as though the word is flickering.

The use of grids was an essential part of building this website, as it allowed for the text to flow and read naturally despite featuring elements that change separately of the rest of the text. The layout consists of three grids, each with three units, representing the beginning of each phrase, followed by the keywords themselves, and finally whatever text follows the keyword and completes the phrase. This was really helpful for building a layout that would be responsive for the words that would change in size and position while hovered, while maintaining the same character spacing of the primary typeface by completely removing padding. The result is text that is readable regardless of the changes in font and scaling, with a layout that reflows accordingly.

Building this design presented a number of challenges, chief among them being the task of finding a way of having interactions with a single element affect other unconnected elements on the page. The initial plan for this was to have the viewer hover on the keyword and see it change to the underlined colour while the rest of the quote changes to grey. When taking this approach, I discovered that I was only able to change a single element at a time which resulted in the only the keyword and one of the units in that grid changing colours while the rest remained black. The solution that I found was to add a unit to each of the grids, a translucent white flex box that sits behind the text but moves forward in z-index along with the the hovered keyword. I found that this had the same effect as what I had expected to see by changing the colour of the auxiliary text, but allowed me to have the colour change apply to all of the text while still adhering to the limitations of this method of only one element being changed at a time.

The overall result is one that I feel communicates the meting of the text in a way that is interactive and as expressive and dynamic as the quote itself. Furthermore, I was even able to embed an Easter egg in the design, by including a portrait of Steve Jobs, created entirely with ASCII characters, that appears in the background when the users hovers on the word do. I felt that this was a nice way to connect the speaker to the text and that having it appear on the final word of the quote would increase the impact of the message.

@Muxlowc

**Comment by muxlowc** [comment]
@shaunmcpherson your grade has been updated - please close this issue
